ProjetoWebWkTechnology/Models/ErrorViewModel.cs
namespace ProjetoWebWkTechnology.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProjetoWebWkTechnology/Controllers/CategoriaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProjetoWebWkTechnology.Domain.Entities;
using ProjetoWebWkTechnology.Service.Interfaces.APIService;


namespace ProjetoWebWkTechnology.Controllers
{
    public class CategoriaController : Controller
    {
        private readonly IProdutoECategoriaAPIService _service;
        public CategoriaController(IProdutoECategoriaAPIService service)
        {
            _service = service;
        }
        [HttpGet]
        public async Task<IActionResult> Index(CancellationToken cancellationToken)
        {
            var resultado = await _service.BuscarTodasCategorias(cancellationToken);
            return View(resultado);
        }

        [HttpGet]
        public async Task<IActionResult> CadastrarCategoria(CancellationToken cancellationToken)
        {
            var categorias = await _service.BuscarTodasCategorias(cancellationToken);
            var selectList = categorias.Select(c => new SelectListItem
            {
                Text = c.Nome,
                Value = c.Id.ToString()
            });
            ViewBag.categoriasExistentes = new SelectList(selectList, "Value", "Text");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CadastrarCategoria(Categoria categoria, CancellationToken cancellationToken)
        {
            await _service.CriarCategoria(categoria, cancellationToken);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Editar(Guid id, CancellationToken cancellationToken)
        {
            var categorias = await _service.BuscarTodasCategorias(cancellationToken);
            var selectList = categorias.Select(c => new SelectListItem
            {
                Text = c.Nome,
                Value = c.Id.ToString()
            });
            ViewBag.categoriasExistentes = new SelectList(selectList, "Value", "Text");
            var resultado = await _service.BuscarCategoriaPorId(id, cancellationToken);
            return View(resultado);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(Categoria categoria, CancellationToken cancellationToken)
        {
            await _service.AtualizarCategoria(categoria, cancellationToken);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Deletar(Guid id, CancellationToken cancellationToken)
        {
            await _service.DeletarCategoria(id, cancellationToken);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Visualizar(Guid id, CancellationToken cancellationToken)
        {
            var result = await _service.BuscarCategoriaPorId(id, cancellationToken);
            return View(result);
        }
    }
}

ProjetoWebWkTechnology/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoWebWkTechnology.Models;
using System.Diagnostics;

namespace ProjetoWebWkTechnology.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjetoWebWkTechnology/Controllers/ProdutoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProjetoWebWkTechnology.Domain.Entities;
using ProjetoWebWkTechnology.Service.Interfaces.APIService;

namespace ProjetoWebWkTechnology.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly IProdutoECategoriaAPIService _service;
        public ProdutoController(IProdutoECategoriaAPIService service)
        {
            _service = service;
        }
        [HttpGet]
        public async Task<IActionResult> Index(CancellationToken cancellationToken)
        {
            var resultado = await _service.BuscarTodosProdutos(cancellationToken);
            return View(resultado);
        }

        [HttpGet]
        public async Task<IActionResult> CadastrarProduto(CancellationToken cancellationToken)
        {
            var categorias = await _service.BuscarTodasCategorias(cancellationToken);
            var selectList = categorias.Select(c => new SelectListItem
            {
                Text = c.Nome,
                Value = c.Id.ToString()
            });
            ViewBag.categoriasExistentes = new SelectList(selectList, "Value", "Text");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CadastrarProduto(Produto produto, CancellationToken cancellationToken)
        {
            await _service.CriarProduto(produto, cancellationToken);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Editar(Guid id, CancellationToken cancellationToken)
        {
            var categorias = await _service.BuscarTodasCategorias(cancellationToken);
            var selectList = categorias.Select(c => new SelectListItem
            {
                Text = c.Nome,
                Value = c.Id.ToString()
            });
            ViewBag.categoriasExistentes = new SelectList(selectList, "Value", "Text");
            var resultado = await _service.BuscarProdutoPorId(id, cancellationToken);
            return View(resultado);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(Produto produto, CancellationToken cancellationToken)
        {
            await _service.AtualizarProduto(produto, cancellationToken);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Deletar(Guid id, CancellationToken cancellationToken)
        {
            await _service.DeletarProduto(id, cancellationToken);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Visualizar(Guid id, CancellationToken cancellationToken)
        {
            var result = await _service.BuscarProdutoPorId(id, cancellationToken);
            return View(result);
        }

    }
}

ProjetoWebWkTechnology/Views/Categoria/CadastrarCategoria.cshtml
@model ProjetoWebWkTechnology.Domain.Entities.Categoria
@{
    ViewData["Title"] = "Cadastrar Categoria";
}


<div class="container-fluid">
    <h1 class="text-center">Cadastro de Categoria</h1>
    <div class="card px-5 py-3">
        <form asp-controller="Categoria" asp-action="CadastrarCategoria" method="post" enctype="multipart/form-data" autocomplete="off">
            <div class="row">

                <div class="form-group col-xl-6 col-md-12">
                    <label asp-for="Nome" class="control-label"></label>
                    <input asp-for="Nome" required type="text" class="form-control" maxlength="50" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                <div class="form-group col-xl-6 col-md-12">
                    <label asp-for="Descricao" class="control-label">Descrição</label>
                    <input asp-for="Descricao" required type="text" class="form-control" maxlength="100" />
                    <span asp-validation-for="Descricao" class="text-danger"></span>
                </div>

                <div class="justify-content-start my-3 col-6" style="display:flex">
                    <a class="btn btn-warning btn-round text-light btn-block" asp-controller="Categoria" asp-action="Index">
                        <i class="bi bi-arrow-left"></i> Voltar
                    </a>
                </div>

                <div class="justify-content-end my-3 col-6" style="display:flex">
                    <button type="submit" class="btn btn-success btn-round  btn-block">
                        <i class="bi bi-save"></i> Salvar
                    </button>
                </div>

            </div>
        </form>
    </div>
</div>

<script type="text/javascript" src="~/js/ValidacaoInputMoeda.js"></script>

ProjetoWebWkTechnology/Views/Categoria/Editar.cshtml
@model ProjetoWebWkTechnology.Domain.Entities.Categoria
@{
    ViewData["Title"] = "Editar Categoria";
}

<div class="container-fluid">
    <h1 class="text-center">Editando Categoria @Model.Nome</h1>
    <div class="card px-5 py-3">
        <form asp-controller="Categoria" asp-action="Editar" method="post" enctype="multipart/form-data" autocomplete="off">
            <div class="row">

                <input type="hidden" asp-for="Id" />

                <div class="form-group col-xl-6 col-md-12">
                    <label asp-for="Nome" class="control-label"></label>
                    <input asp-for="Nome" type="text" class="form-control" maxlength="50" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                <div class="form-group col-xl-6 col-md-12">
                    <label asp-for="Descricao" class="control-label">Descrição</label>
                    <input asp-for="Descricao" type="text" class="form-control" maxlength="100" />
                    <span asp-validation-for="Descricao" class="text-danger"></span>
                </div>
                
                <div class="justify-content-start my-3 col-6" style="display:flex">
                    <a class="btn btn-warning btn-round text-light btn-block" asp-controller="Categoria" asp-action="Index">
                        <i class="bi bi-arrow-left"></i> Voltar
                    </a>
                </div>

                <div class="justify-content-end my-3 col-6" style="display:flex">
                    <button type="submit" class="btn btn-success btn-round  btn-block">
                        <i class="bi bi-save"></i> Salvar
                    </button>
                </div>

            </div>
        </form>
    </div>
</div>



<script type="text/javascript" src="~/js/ValidacaoInputMoeda.js"></script>

ProjetoWebWkTechnology/Views/Categoria/Index.cshtml
@model List<ProjetoWebWkTechnology.Domain.Entities.Categoria>
@{
    ViewData["Title"] = "Página de Categorias";
}

<link rel="stylesheet" type="text/css" href="~/lib/dataTables/datatables.min.css" />

<div class="container-fluid">
    <h1 class="text-center">Lista de Categorias</h1>
    <div class="justify-content-end my-3" style="display:flex">
        <a class="btn btn-success text-light" asp-controller="Categoria" asp-action="CadastrarCategoria"><i class="bi bi-plus-circle"></i> Cadastrar Produto</a>
    </div>

    <div class="card px-5 py-3">
        <table id="tabelaCategoria" class="display" style="width:100%">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Descrição</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var categoria in Model)
                {
                    <tr>
                        <td>@categoria.Nome</td>
                        <td>@categoria.Descricao</td>
                        <td>
                            <div class="justify-content-around" style="display:flex">
                                <a class="btn btn-primary text-light" asp-controller="Categoria" asp-action="Visualizar" asp-route-id="@categoria.Id"><i class="bi bi-eye"></i> Visualizar</a>
                                <a class="btn btn-warning text-light" asp-controller="Categoria" asp-action="Editar" asp-route-id="@categoria.Id"><i class="bi bi-pencil-square"></i> Editar</a>
                                <a class="btn btn-danger text-light" asp-controller="Categoria" asp-action="Deletar" asp-route-id="@categoria.Id"><i class="bi bi-trash"></i>Excluir</a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>
       $(document).ready(function() {
        $('#tabelaCategoria').DataTable(configuracaoPadraoDatatables);
    } );
</script>

ProjetoWebWkTechnology/Views/Categoria/Visualizar.cshtml
@model ProjetoWebWkTechnology.Domain.Entities.Categoria
@{
    ViewData["Title"] = "Visualizar Categoria";
}


<div class="container-fluid">
    <h1 class="text-center">Cadastro de Categorias</h1>
    <div class="card px-5 py-3">
        <div class="row">

            <div class="form-group col-xl-6 col-md-12">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" disabled type="text" class="form-control" maxlength="50" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group col-xl-6 col-md-12">
                <label asp-for="Descricao" class="control-label">Descrição</label>
                <input asp-for="Descricao" disabled type="text" class="form-control" maxlength="100" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>

            <div class="justify-content-start my-3 col-6" style="display:flex">
                <a class="btn btn-warning btn-round text-light btn-block" asp-controller="Categoria" asp-action="Index">
                    <i class="bi bi-arrow-left"></i> Voltar
                </a>
            </div>
        </div>
    </div>
</div>

ProjetoWebWkTechnology/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center my-5">
    <h1 class="display-4 mb-1"><b>Bem-Vindo</b></h1>
    <p>Este projeto foi criado por <b>Arlisson Jesus Barbosa Menacho</b>, como participação de um teste técnico para a empresa <b>Wk Technology</b></p>
    <ul class="justify-content-start">
      <b>  Dados Para contato</b>
        <li>
           <b> Linkedin:</b>  <a href="https://www.linkedin.com/in/arlissonmenacho/">https://www.linkedin.com/in/arlissonmenacho/</a>
        </li>
        <li>
           <b>Número de telefone:</b>  (69) 9 9361-0339
        </li>
        <li>
           <b> E-mail:</b>  Arlissonmenacho@gmail.com
        </li>
    </ul>
</div>

ProjetoWebWkTechnology/Views/Produto/CadastrarProduto.cshtml
@model ProjetoWebWkTechnology.Domain.Entities.Produto
@{
    ViewData["Title"] = "Cadastrar Produto";
}


<div class="container-fluid">
    <h1 class="text-center">Cadastro de Produtos</h1>
    <div class="card px-5 py-3">
        <form asp-controller="Produto" asp-action="CadastrarProduto" method="post" enctype="multipart/form-data" autocomplete="off">
            <div class="row">

                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="CategoriaId" />

                <div class="form-group col-xl-6 col-md-12">
                    <label asp-for="Nome" class="control-label"></label>
                    <input asp-for="Nome" required type="text" class="form-control" maxlength="50" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                <div class="form-group col-xl-6 col-md-12">
                    <label asp-for="Descricao" class="control-label">Descrição</label>
                    <input asp-for="Descricao" required type="text" class="form-control" maxlength="100" />
                    <span asp-validation-for="Descricao" class="text-danger"></span>
                </div>

                <div class="form-group col-xl-6 col-md-12">
                    <label asp-for="Marca" class="control-label"></label>
                    <input asp-for="Marca" required type="text" class="form-control" maxlength="50" />
                    <span asp-validation-for="Marca" class="text-danger"></span>
                </div>

                <div class="form-group col-xl-6 col-md-12">
                    <label asp-for="PrecoInformado" class="control-label">Preço</label>
                    <input asp-for="PrecoInformado" id="currency" required type="text" class="form-control" step="any" maxlength="50" />
                    <span asp-validation-for="PrecoInformado" class="text-danger"></span>
                </div>

                <div class="form-group col-md-12 col-sm-12">
                    <label asp-for="CategoriaSelecionada">Categoria</label>
                    <select asp-for="CategoriaSelecionada" required class="form-control selectpicker" asp-items="ViewBag.categoriasExistentes" data-live-search="true" data-dropup-auto="false">
                        <option value="">Selecione...</option>
                    </select>
                </div>

                <div class="justify-content-start my-3 col-6" style="display:flex">
                    <a class="btn btn-warning btn-round text-light btn-block" asp-controller="Produto" asp-action="Index">
                        <i class="bi bi-arrow-left"></i> Voltar
                    </a>
                </div>

                <div class="justify-content-end my-3 col-6" style="display:flex">
                    <button type="submit" class="btn btn-success btn-round  btn-block">
                        <i class="bi bi-save"></i> Salvar
                    </button>
                </div>

            </div>
        </form>
    </div>
</div>

<script type="text/javascript" src="~/js/ValidacaoInputMoeda.js"></script>

ProjetoWebWkTechnology/Views/Produto/Editar.cshtml
@model ProjetoWebWkTechnology.Domain.Entities.Produto
@{
    ViewData["Title"] = "Editar Produto";
}

<div class="container-fluid">
    <h1 class="text-center">Editando Produto @Model.Nome</h1>
    <div class="card px-5 py-3">
        <form asp-controller="Produto" asp-action="Editar" method="post" enctype="multipart/form-data" autocomplete="off">
            <div class="row">

                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="CategoriaId" />

                    <div class="form-group col-xl-6 col-md-12">
                    <label asp-for="Nome" class="control-label"></label>
                    <input asp-for="Nome" type="text" class="form-control" maxlength="50" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                    <div class="form-group col-xl-6 col-md-12">
                    <label asp-for="Descricao" class="control-label">Descrição</label>
                    <input asp-for="Descricao" type="text" class="form-control" maxlength="100" />
                    <span asp-validation-for="Descricao" class="text-danger"></span>
                </div>

                    <div class="form-group col-xl-6 col-md-12">
                    <label asp-for="Marca" class="control-label"></label>
                    <input asp-for="Marca" type="text" class="form-control" maxlength="50" />
                    <span asp-validation-for="Marca" class="text-danger"></span>
                </div>

                    <div class="form-group col-xl-6 col-md-12">
                    <label asp-for="PrecoInformado" class="control-label">Preço</label>
                    <input asp-for="PrecoInformado" id="currency" type="text" class="form-control" maxlength="50" />
                    <span asp-validation-for="PrecoInformado" class="text-danger"></span>
                </div>

                <div class="form-group col-md-12 col-sm-12">
                    <label asp-for="CategoriaSelecionada">Categoria</label>
                    <select asp-for="CategoriaSelecionada" class="form-control selectpicker" asp-items="ViewBag.categoriasExistentes" data-live-search="true" data-dropup-auto="false">
                        <option value="">Selecione...</option>
                    </select>
                </div>

                <div class="justify-content-start my-3 col-6" style="display:flex">
                    <a class="btn btn-warning btn-round text-light btn-block" asp-controller="Produto" asp-action="Index">
                        <i class="bi bi-arrow-left"></i> Voltar
                    </a>
                </div>

                <div class="justify-content-end my-3 col-6" style="display:flex">
                    <button type="submit" class="btn btn-success btn-round  btn-block">
                        <i class="bi bi-save"></i> Salvar
                    </button>
                </div>

            </div>
        </form>
    </div>
</div>



<script type="text/javascript" src="~/js/ValidacaoInputMoeda.js"></script>

ProjetoWebWkTechnology/Views/Produto/Index.cshtml
@model List<ProjetoWebWkTechnology.Domain.Entities.Produto>
@{
    ViewData["Title"] = "Página de Produtos";
}

<link rel="stylesheet" type="text/css" href="~/lib/dataTables/datatables.min.css" />

<div class="container-fluid">
    <h1 class="text-center">Lista de Produtos</h1>
    <div class="justify-content-end my-3" style="display:flex">
        <a class="btn btn-success text-light" asp-controller="Produto" asp-action="CadastrarProduto"><i class="bi bi-plus-circle"></i> Cadastrar Produto</a>
    </div>
     
    <div class="card px-5 py-3">
        <table id="tabelaProdutos" class="display" style="width:100%">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Descrição</th>
                    <th>Preço</th>
                    <th>Marca</th>
                    <th>Categoria</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var produto in Model)
                {
                    <tr>
                        <td>@produto.Nome</td>
                        <td>@produto.Descricao</td>
                        <td>R$ @produto.Preco</td>
                        <td>@produto.Marca</td>
                        <td>@produto.Categoria.Nome</td>
                        <td>
                            <div class="justify-content-around" style="display:flex">
                                <a class="btn btn-primary text-light" asp-controller="Produto" asp-action="Visualizar" asp-route-id="@produto.Id"><i class="bi bi-eye"></i> Visualizar</a>
                                <a class="btn btn-warning text-light" asp-controller="Produto" asp-action="Editar" asp-route-id="@produto.Id"><i class="bi bi-pencil-square"></i> Editar</a>
                                <a class="btn btn-danger text-light" asp-controller="Produto" asp-action="Deletar" asp-route-id="@produto.Id" method="delete"><i class="bi bi-trash"></i>Excluir</a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>
       $(document).ready(function() {
        $('#tabelaProdutos').DataTable(configuracaoPadraoDatatables);
    } );
</script>

ProjetoWebWkTechnology/Views/Produto/Visualizar.cshtml
@model ProjetoWebWkTechnology.Domain.Entities.Produto
@{
    ViewData["Title"] = "Visualizar Produto";
}


<div class="container-fluid">
    <h1 class="text-center">Cadastro de Produtos</h1>
    <div class="card px-5 py-3">
            <div class="row">


                   <div class="form-group col-xl-6 col-md-12">
                    <label asp-for="Nome" class="control-label"></label>
                    <input asp-for="Nome" disabled type="text" class="form-control" maxlength="50" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                   <div class="form-group col-xl-6 col-md-12">
                    <label asp-for="Descricao" class="control-label">Descrição</label>
                    <input asp-for="Descricao" disabled type="text" class="form-control" maxlength="100" />
                    <span asp-validation-for="Descricao" class="text-danger"></span>
                </div>

                  <div class="form-group col-xl-6 col-md-12">
                    <label asp-for="Marca" class="control-label"></label>
                    <input asp-for="Marca" disabled type="text" class="form-control" maxlength="50" />
                    <span asp-validation-for="Marca" class="text-danger"></span>
                </div>

                   <div class="form-group col-xl-6 col-md-12">
                    <label asp-for="PrecoInformado" class="control-label">Preço</label>
                    <input asp-for="PrecoInformado" disabled type="text" class="form-control" step="any" maxlength="50" />
                    <span asp-validation-for="PrecoInformado" class="text-danger"></span>
                </div>

                   <div class="form-group col-12">
                    <label asp-for="Categoria.Nome">Categoria</label>
                    <input asp-for="Categoria.Nome" disabled type="text" class="form-control" step="any" maxlength="50" />
                     <span asp-validation-for="Categoria.Nome" class="text-danger"></span>
                </div>

                <div class="justify-content-start my-3 col-6" style="display:flex">
                    <a class="btn btn-warning btn-round text-light btn-block" asp-controller="Produto" asp-action="Index">
                        <i class="bi bi-arrow-left"></i> Voltar
                    </a>
                </div>
            </div>
    </div>
</div>

ProjetoWebWkTechnology/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetoWebWkTechnology</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript"></script>
	@*<script src="javascripts/jquery.maskMoney.min.js" type="text/javascript"></script>*@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjetoWebWkTechnology.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Projeto WEB WK Tecnology</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Produtos</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categoria" asp-action="Index">Categoria</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Projeto Web Wk Technology - Projeto criado por Arlisson Jesus Barbosa Menacho
        </div>
    </footer>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="~/lib/jquery-maskmoney/dist/jquery.maskMoney.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" src="~/lib/dataTables/pdfmake.min.js"></script>
    <script type="text/javascript" src="~/lib/dataTables/vfs_fonts.js"></script>
    <script type="text/javascript" src="~/lib/dataTables/datatables.min.js"></script>
    <script type="text/javascript" src="~/lib/dataTables/configuracao-padrao-datatables.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>